openapi: "3.0.0"
info:
    version: "1.0.0"
    title: "Sample API"
    description: Buy or rent spacecrafts
servers:
    - url: "https://localhost:7177"
paths:    
    /odata/Nutriments?$top={top}&$skip={skip}:
        parameters:
            - name: top
              description: items size number
              in: path
              required: true
              schema:
                  $ref: "#/components/schemas/top"
            - name: skip
              description: skipped items number
              in: path
              required: true
              schema:
                  $ref: "#/components/schemas/skip"
        get:
            summary: Get Nutriments
            responses:
                "200":
                    description: Nutriment array
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Spacecraft"
                500:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
    /odata/Nutriments({id}):
        parameters:
            - name: id
              description: identifier
              in: path
              required: true
              schema:
                  $ref: "#/components/schemas/id"
        get:
            summary: Get Nutriment by id
            responses:
                "200":
                    description: Nutriment
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Nutriment"
                500:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"    
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Nutriment"
            responses:
                "204":
                    description: Nutriment updated partialy
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Nutriment"
                500:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
            
        patch:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Nutriment"
            responses:
                "204":
                    description: Nutriment updated partialy
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Nutriment"
                500:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
        delete:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Nutriment"
            responses:
                "204":
                    description: Nutriment deleted
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Nutriment"
                500:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"

components:
    schemas:
        id:
            description: The unique identifier
            type: string
        top:
            description: The number of the items size 
            type: integer
        skip:
            description: The number of the skipped items 
            type: integer
        Nutriment:
            type: object
            properties:
                Id:
                    type: string
                Name:
                    type: string
        Error:
            type: object
            required:
                - message
            properties:
                message:
                    description: A human readable error message
                    type: string
    securitySchemes:
        ApiKey:
            type: apiKey
            in: header
            name: X-Api-Key
security:
    - ApiKey: []
