apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: certificate-claim
  name: certificate-claim
  namespace: {{ .Values.applicationName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: certificate-pv-volume
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Mi
  phase: Bound
