apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: db-claim
  name: db-claim
  namespace: baka-chief
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: baka-chief-db-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  phase: Bound
