apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: baka-chief-db-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /baka-media/web/baka-chief/database
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
