using System.ComponentModel.DataAnnotations;
using CsvHelper.Configuration.Attributes;

namespace bakaChiefApplication.API.DatabaseModels;

[Delimiter(";")]
public class ProductInfo
{
    [Key]
    public string code { get; set; } = Guid.NewGuid().ToString();
    public string? url { get; set; }
    public string? creator { get; set; }
    public long? created_t { get; set; }
    public DateTime? created_datetime { get; set; }
    public long? last_modified_t { get; set; }
    public DateTime? last_modified_datetime { get; set; }
    public string? last_modified_by { get; set; }
    public string? product_name { get; set; }
    public string? abbreviated_product_name { get; set; }
    public string? generic_name { get; set; }
    public string? quantity { get; set; }
    public string? packaging { get; set; }
    public string? packaging_tags { get; set; }
    public string? packaging_fr { get; set; }
    public string? packaging_text { get; set; }
    public string? brands { get; set; }
    public string? brands_tags { get; set; }
    public string? categories { get; set; }
    public string? categories_tags { get; set; }
    public string? categories_fr { get; set; }
    public string? origins { get; set; }
    public string? origins_tags { get; set; }
    public string? origins_fr { get; set; }
    public string? manufacturing_places { get; set; }
    public string? manufacturing_places_tags { get; set; }
    public string? labels { get; set; }
    public string? labels_tags { get; set; }
    public string? labels_fr { get; set; }
    public string? emb_codes { get; set; }
    public string? emb_codes_tags { get; set; }
    public string? first_packaging_code_geo { get; set; }
    public string? cities { get; set; }
    public string? cities_tags { get; set; }
    public string? purchase_places { get; set; }
    public string? stores { get; set; }
    public string? countries { get; set; }
    public string? countries_tags { get; set; }
    public string? countries_fr { get; set; }
    public string? ingredients_text { get; set; }
    public string? ingredients_tags { get; set; }
    public string? ingredients_analysis_tags { get; set; }
    public string? allergens { get; set; }
    public string? allergens_fr { get; set; }
    public string? traces { get; set; }
    public string? traces_tags { get; set; }
    public string? traces_fr { get; set; }
    public string? serving_size { get; set; }
    public string? serving_quantity { get; set; }
    public string? no_nutrition_data { get; set; }
    public string? additives_n { get; set; }
    public string? additives { get; set; }
    public string? additives_tags { get; set; }
    public string? additives_fr { get; set; }
    public string? nutriscore_score { get; set; }
    public string? nutriscore_grade { get; set; }
    public string? nova_group { get; set; }
    public string? pnns_groups_1 { get; set; }
    public string? pnns_groups_2 { get; set; }
    public string? food_groups { get; set; }
    public string? food_groups_tags { get; set; }
    public string? food_groups_fr { get; set; }
    public string? states { get; set; }
    public string? states_tags { get; set; }
    public string? states_fr { get; set; }
    public string? brand_owner { get; set; }
    public string? ecoscore_score { get; set; }
    public string? ecoscore_grade { get; set; }
    public string? nutrient_levels_tags { get; set; }
    public string? product_quantity { get; set; }
    public string? owner { get; set; }
    public string? data_quality_errors_tags { get; set; }
    public string? unique_scans_n { get; set; }
    public string? popularity_tags { get; set; }
    public string? completeness { get; set; }
    public string? last_image_t { get; set; }
    public string? last_image_datetime { get; set; }
    public string? main_category { get; set; }
    public string? main_category_fr { get; set; }
    public string? image_url { get; set; }
    public string? image_small_url { get; set; }
    public string? image_ingredients_url { get; set; }
    public string? image_ingredients_small_url { get; set; }
    public string? image_nutrition_url { get; set; }
    public string? image_nutrition_small_url { get; set; }
    public string? energy_kj_100g { get; set; }
    public string? energy_kcal_100g { get; set; }
    public string? energy_100g { get; set; }
    public string? energy_from_fat_100g { get; set; }
    public string? fat_100g { get; set; }
    public string? saturated_fat_100g { get; set; }
    public string? butyric_acid_100g { get; set; }
    public string? caproic_acid_100g { get; set; }
    public string? caprylic_acid_100g { get; set; }
    public string? capric_acid_100g { get; set; }
    public string? lauric_acid_100g { get; set; }
    public string? myristic_acid_100g { get; set; }
    public string? palmitic_acid_100g { get; set; }
    public string? stearic_acid_100g { get; set; }
    public string? arachidic_acid_100g { get; set; }
    public string? behenic_acid_100g { get; set; }
    public string? lignoceric_acid_100g { get; set; }
    public string? cerotic_acid_100g { get; set; }
    public string? montanic_acid_100g { get; set; }
    public string? melissic_acid_100g { get; set; }
    public string? unsaturated_fat_100g { get; set; }
    public string? monounsaturated_fat_100g { get; set; }
    public string? polyunsaturated_fat_100g { get; set; }
    public string? omega_3_fat_100g { get; set; }
    public string? alpha_linolenic_acid_100g { get; set; }
    public string? eicosapentaenoic_acid_100g { get; set; }
    public string? docosahexaenoic_acid_100g { get; set; }
    public string? omega_6_fat_100g { get; set; }
    public string? linoleic_acid_100g { get; set; }
    public string? arachidonic_acid_100g { get; set; }
    public string? gamma_linolenic_acid_100g { get; set; }
    public string? dihomo_gamma_linolenic_acid_100g { get; set; }
    public string? omega_9_fat_100g { get; set; }
    public string? oleic_acid_100g { get; set; }
    public string? elaidic_acid_100g { get; set; }
    public string? gondoic_acid_100g { get; set; }
    public string? mead_acid_100g { get; set; }
    public string? erucic_acid_100g { get; set; }
    public string? nervonic_acid_100g { get; set; }
    public string? trans_fat_100g { get; set; }
    public string? cholesterol_100g { get; set; }
    public string? carbohydrates_100g { get; set; }
    public string? sugars_100g { get; set; }
    public string? added_sugars_100g { get; set; }
    public string? sucrose_100g { get; set; }
    public string? glucose_100g { get; set; }
    public string? fructose_100g { get; set; }
    public string? lactose_100g { get; set; }
    public string? maltose_100g { get; set; }
    public string? maltodextrins_100g { get; set; }
    public string? starch_100g { get; set; }
    public string? polyols_100g { get; set; }
    public string? erythritol_100g { get; set; }
    public string? fiber_100g { get; set; }
    public string? soluble_fiber_100g { get; set; }
    public string? insoluble_fiber_100g { get; set; }
    public string? proteins_100g { get; set; }
    public string? casein_100g { get; set; }
    public string? serum_proteins_100g { get; set; }
    public string? nucleotides_100g { get; set; }
    public string? salt_100g { get; set; }
    public string? added_salt_100g { get; set; }
    public string? sodium_100g { get; set; }
    public string? alcohol_100g { get; set; }
    public string? vitamin_a_100g { get; set; }
    public string? beta_carotene_100g { get; set; }
    public string? vitamin_d_100g { get; set; }
    public string? vitamin_e_100g { get; set; }
    public string? vitamin_k_100g { get; set; }
    public string? vitamin_c_100g { get; set; }
    public string? vitamin_b1_100g { get; set; }
    public string? vitamin_b2_100g { get; set; }
    public string? vitamin_pp_100g { get; set; }
    public string? vitamin_b6_100g { get; set; }
    public string? vitamin_b9_100g { get; set; }
    public string? folates_100g { get; set; }
    public string? vitamin_b12_100g { get; set; }
    public string? biotin_100g { get; set; }
    public string? pantothenic_acid_100g { get; set; }
    public string? silica_100g { get; set; }
    public string? bicarbonate_100g { get; set; }
    public string? potassium_100g { get; set; }
    public string? chloride_100g { get; set; }
    public string? calcium_100g { get; set; }
    public string? phosphorus_100g { get; set; }
    public string? iron_100g { get; set; }
    public string? magnesium_100g { get; set; }
    public string? zinc_100g { get; set; }
    public string? copper_100g { get; set; }
    public string? manganese_100g { get; set; }
    public string? fluoride_100g { get; set; }
    public string? selenium_100g { get; set; }
    public string? chromium_100g { get; set; }
    public string? molybdenum_100g { get; set; }
    public string? iodine_100g { get; set; }
    public string? caffeine_100g { get; set; }
    public string? taurine_100g { get; set; }
    public string? ph_100g { get; set; }
    public string? fruits_vegetables_nuts_100g { get; set; }
    public string? fruits_vegetables_nuts_dried_100g { get; set; }
    public string? fruits_vegetables_nuts_estimate_100g { get; set; }
    public string? fruits_vegetables_nuts_estimate_from_ingredients_100g { get; set; }
    public string? collagen_meat_protein_ratio_100g { get; set; }
    public string? cocoa_100g { get; set; }
    public string? chlorophyl_100g { get; set; }
    public string? carbon_footprint_100g { get; set; }
    public string? carbon_footprint_from_meat_or_fish_100g { get; set; }
    public string? nutrition_score_fr_100g { get; set; }
    public string? nutrition_score_uk_100g { get; set; }
    public string? glycemic_index_100g { get; set; }
    public string? water_hardness_100g { get; set; }
    public string? choline_100g { get; set; }
    public string? phylloquinone_100g { get; set; }
    public string? beta_glucan_100g { get; set; }
    public string? inositol_100g { get; set; }
    public string? carnitine_100g { get; set; }
    public string? sulphate_100g { get; set; }
    public string? nitrate_100g { get; set; }
}