name: baka chief api CICD

on:
  push:
    branches: [ "main" ]

jobs:
  Continuous-integration:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      
    - name: Install SDK
      run: sudo apt-get install dotnet-sdk-7.0
        
    - name: Install dependencies
      working-directory: /home/runner/work/baka-chief-API/baka-chief-API/bakaChiefApplication.API
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal

  Continuous_delivery:
    needs: [Continuous-integration]
    runs-on: ubuntu-latest
    env:
      Repo: /home/runner/work/baka-chief-API/baka-chief-API/bakaChiefApplication.API/bakaChiefApplication.API/
      DockerImageName: bakayarusama/music_player:${{  github.ref_name }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} 
             -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      working-directory: /home/runner/work/baka-chief-API/baka-chief-API/bakaChiefApplication.API/bakaChiefApplication.API/
      run: docker build -t $DockerImageName $Repo

    - name: Publish Docker image
      run: docker push $DockerImageName
